// =============================================================================
// audio.js — every sound in the game, made from scratch.
//
// There are no sound files. Every noise here is generated by the browser on
// the spot out of two ingredients:
//
//   TONES  — a pure pitch. Sweep one downward fast and you have a gunshot's
//            "crack"; sweep it slowly and you have a thud.
//   NOISE  — static, like an untuned radio. Filtered and cut short it becomes
//            the blast of a shotgun or the crunch of splintering wood.
//
// That's how 8-bit consoles did it, which is why it fits — and it means no
// asset files, no loading, and a new sound is a few numbers rather than a
// recording session.
//
// Browsers refuse to make noise until the player has interacted with the page,
// so the whole thing wakes up on the first key or click.
// =============================================================================

import { settings } from './settings.js';

let context = null;
let masterGain = null;
let noiseBuffer = null;

// Wake the audio up. Safe to call as often as you like — it only does
// anything the first time, and browsers only allow it after a real keypress
// or click, which is why it's called from the input handlers.
export function wakeAudio() {
  if (context) {
    if (context.state === 'suspended') context.resume();
    return;
  }

  const AudioContextClass = window.AudioContext || window.webkitAudioContext;
  if (!AudioContextClass) return;

  context = new AudioContextClass();
  masterGain = context.createGain();
  masterGain.gain.value = settings.volume;
  masterGain.connect(context.destination);

  noiseBuffer = makeNoiseBuffer();
}

export function setVolume(value) {
  settings.volume = Math.min(1, Math.max(0, value));
  if (masterGain) masterGain.gain.value = settings.volume;
}

function canPlay() {
  return context !== null && settings.volume > 0;
}

// A second of static, generated once and reused for every noise-based sound.
function makeNoiseBuffer() {
  const length = context.sampleRate;
  const buffer = context.createBuffer(1, length, context.sampleRate);
  const data = buffer.getChannelData(0);

  for (let i = 0; i < length; i++) {
    data[i] = Math.random() * 2 - 1;
  }

  return buffer;
}

// -----------------------------------------------------------------------------
// THE TWO INGREDIENTS
// -----------------------------------------------------------------------------

// A pitch that slides from one frequency to another while fading out.
function tone({ from, to, seconds, volume = 0.3, shape = 'square', delay = 0 }) {
  if (!canPlay()) return;

  const start = context.currentTime + delay;
  const oscillator = context.createOscillator();
  const gain = context.createGain();

  oscillator.type = shape;
  oscillator.frequency.setValueAtTime(from, start);

  // Exponential rather than linear, because pitch is heard exponentially —
  // a straight-line slide sounds like it stalls at the bottom.
  oscillator.frequency.exponentialRampToValueAtTime(Math.max(1, to), start + seconds);

  gain.gain.setValueAtTime(volume, start);
  gain.gain.exponentialRampToValueAtTime(0.0001, start + seconds);

  oscillator.connect(gain);
  gain.connect(masterGain);
  oscillator.start(start);
  oscillator.stop(start + seconds + 0.02);
}

// A burst of static, shaped by a filter. This is where the body of a gunshot
// comes from — the bang, as opposed to the crack.
function noise({
  seconds,
  volume = 0.3,
  filterFrom = 4000,
  filterTo = 400,
  filterType = 'lowpass',
  delay = 0,
}) {
  if (!canPlay()) return;

  const start = context.currentTime + delay;
  const source = context.createBufferSource();
  const filter = context.createBiquadFilter();
  const gain = context.createGain();

  source.buffer = noiseBuffer;
  source.playbackRate.value = 0.8 + Math.random() * 0.4;

  filter.type = filterType;
  filter.frequency.setValueAtTime(filterFrom, start);
  filter.frequency.exponentialRampToValueAtTime(Math.max(1, filterTo), start + seconds);

  gain.gain.setValueAtTime(volume, start);
  gain.gain.exponentialRampToValueAtTime(0.0001, start + seconds);

  source.connect(filter);
  filter.connect(gain);
  gain.connect(masterGain);
  source.start(start);
  source.stop(start + seconds + 0.02);
}

// A little random wobble on pitch. Without it, an uzi firing eighteen rounds a
// second sounds like one long buzz instead of eighteen shots.
function jitter(amount = 0.12) {
  return 1 + (Math.random() - 0.5) * 2 * amount;
}

// -----------------------------------------------------------------------------
// GUNS
// -----------------------------------------------------------------------------

export function playWeapon(weaponId) {
  switch (weaponId) {
    case 'shotgun':
      return playShotgun();
    case 'uzi':
      return playUzi();
    case 'grenades':
      return playThrow();
    default:
      return playPistol();
  }
}

// A sharp crack over a short bang. Tight and dry.
function playPistol() {
  const wobble = jitter();
  tone({ from: 460 * wobble, to: 70, seconds: 0.07, volume: 0.22 });
  noise({ seconds: 0.05, volume: 0.24, filterFrom: 6000, filterTo: 900 });
}

// Much more body, much slower decay. The low tone underneath is what makes it
// feel heavy rather than just loud.
function playShotgun() {
  const wobble = jitter(0.08);
  noise({ seconds: 0.22, volume: 0.34, filterFrom: 3200, filterTo: 180 });
  tone({ from: 150 * wobble, to: 42, seconds: 0.18, volume: 0.26 });
}

// Higher, shorter and drier than the pistol, with a wide wobble so a burst
// reads as many separate rounds.
function playUzi() {
  const wobble = jitter(0.22);
  tone({ from: 620 * wobble, to: 160, seconds: 0.035, volume: 0.14 });
  noise({ seconds: 0.03, volume: 0.13, filterFrom: 7000, filterTo: 1800 });
}

// Not a gunshot at all — a short swipe of air.
function playThrow() {
  noise({
    seconds: 0.18,
    volume: 0.16,
    filterFrom: 400,
    filterTo: 2600,
    filterType: 'bandpass',
  });
}

export function playDryFire() {
  tone({ from: 1400, to: 900, seconds: 0.02, volume: 0.08, shape: 'square' });
}

// Two clicks: the magazine out, then the magazine in.
export function playReload(reloadSeconds) {
  tone({ from: 900, to: 500, seconds: 0.04, volume: 0.12, shape: 'square' });
  tone({
    from: 700,
    to: 340,
    seconds: 0.05,
    volume: 0.14,
    shape: 'square',
    delay: Math.max(0.05, reloadSeconds - 0.12),
  });
}

// -----------------------------------------------------------------------------
// EVERYTHING ELSE
// -----------------------------------------------------------------------------

export function playHit() {
  tone({ from: 900 * jitter(0.2), to: 400, seconds: 0.03, volume: 0.09, shape: 'triangle' });
}

export function playHeadshot() {
  tone({ from: 1500, to: 700, seconds: 0.07, volume: 0.18, shape: 'square' });
}

export function playScalperDown() {
  tone({ from: 420 * jitter(0.25), to: 90, seconds: 0.16, volume: 0.15, shape: 'triangle' });
  noise({ seconds: 0.1, volume: 0.08, filterFrom: 2200, filterTo: 300 });
}

export function playExplosion() {
  noise({ seconds: 0.55, volume: 0.42, filterFrom: 2400, filterTo: 90 });
  tone({ from: 110, to: 28, seconds: 0.45, volume: 0.3, shape: 'sine' });
}

export function playBarricadeHit() {
  tone({ from: 190 * jitter(0.25), to: 70, seconds: 0.07, volume: 0.1, shape: 'triangle' });
}

export function playBarricadeBreak() {
  noise({ seconds: 0.7, volume: 0.4, filterFrom: 1800, filterTo: 120 });
  tone({ from: 220, to: 40, seconds: 0.5, volume: 0.3, shape: 'sawtooth' });
}

export function playBossSlam() {
  noise({ seconds: 0.5, volume: 0.45, filterFrom: 1400, filterTo: 70 });
  tone({ from: 90, to: 25, seconds: 0.5, volume: 0.38, shape: 'sine' });
}

// A rising two-note sting — the audio version of the weak point lighting up.
export function playWeakPointOpen() {
  tone({ from: 600, to: 900, seconds: 0.09, volume: 0.22, shape: 'square' });
  tone({ from: 900, to: 1300, seconds: 0.12, volume: 0.2, shape: 'square', delay: 0.09 });
}

export function playBossStaggered() {
  tone({ from: 300, to: 70, seconds: 0.4, volume: 0.3, shape: 'sawtooth' });
}

export function playNightStart() {
  const notes = [330, 440, 550];
  notes.forEach((frequency, index) => {
    tone({ from: frequency, to: frequency, seconds: 0.11, volume: 0.16, delay: index * 0.1 });
  });
}

export function playSunrise() {
  const notes = [440, 550, 660, 880];
  notes.forEach((frequency, index) => {
    tone({ from: frequency, to: frequency, seconds: 0.16, volume: 0.17, delay: index * 0.12 });
  });
}

export function playGameOver() {
  const notes = [440, 350, 260, 160];
  notes.forEach((frequency, index) => {
    tone({ from: frequency, to: frequency, seconds: 0.22, volume: 0.2, shape: 'triangle', delay: index * 0.18 });
  });
}

export function playMenuMove() {
  tone({ from: 700, to: 700, seconds: 0.03, volume: 0.09, shape: 'square' });
}

export function playMenuConfirm() {
  tone({ from: 600, to: 950, seconds: 0.08, volume: 0.14, shape: 'square' });
}

export function playPurchase() {
  tone({ from: 700, to: 700, seconds: 0.06, volume: 0.15, shape: 'square' });
  tone({ from: 1050, to: 1050, seconds: 0.09, volume: 0.15, shape: 'square', delay: 0.06 });
}

export function playDenied() {
  tone({ from: 200, to: 120, seconds: 0.12, volume: 0.14, shape: 'sawtooth' });
}
